import { Page, Locator, expect } from '@playwright/test';

/**
 * Page Object Model representing MainSearch (Suche & Filter von Turnieren & Wettbewerben).
 * Kapselt alle Formularfelder (HTML-IDs per #MainSearch_*), Radio-Buttons und Ergebnistabellen.
 */
export class MainSearchPage {
  readonly page: Page;

  // Search Input Fields (exact HTML-IDs generated by MainSearch.scala)
  readonly inputTitle: Locator;
  readonly inputOrganizer: Locator;
  readonly inputDate: Locator;

  // Type Radio Buttons
  readonly radioTypeAll: Locator;
  readonly radioTypeTourney: Locator;
  readonly radioTypeComp: Locator;

  // Search Results Table & Header
  readonly headerDateSort: Locator;
  readonly sortIcon: Locator;
  readonly resultsBody: Locator;
  readonly resultCount: Locator;
  readonly resultRows: Locator;

  constructor(page: Page) {
    this.page = page;

    // Encapsulate exact HTML-IDs generated by ScalaJS in MainSearch.scala
    this.inputTitle = page.locator('#MainSearch_IdInputTitle');
    this.inputOrganizer = page.locator('#MainSearch_IdInputOrganizer');
    this.inputDate = page.locator('#MainSearch_IdInputDate');

    this.radioTypeAll = page.locator('#MainSearch_RadioTypeAllId');
    this.radioTypeTourney = page.locator('#MainSearch_RadioTypeTourneyId');
    this.radioTypeComp = page.locator('#MainSearch_RadioTypeCompId');

    this.headerDateSort = page.locator('#MainSearch_IdHeaderDate');
    this.sortIcon = page.locator('#MainSearch_IdSortIcon');
    this.resultsBody = page.locator('#MainSearch_IdResultsBody');
    this.resultCount = page.locator('#MainSearch_IdResultCount');
    
    // Result rows matching id starting with MainSearch_InputResultId
    this.resultRows = page.locator('tr[id^="MainSearch_InputResultId"]');
  }

  /**
   * Navigates directly to the MainSearch hash page.
   */
  async goto() {
    await this.page.goto('/');
    await this.page.waitForLoadState('domcontentloaded');
    await this.page.evaluate(() => {
      if (typeof (window as any).appLoadPage === 'function') {
        (window as any).appLoadPage('MainSearch', '');
      }
    });
    await expect(this.inputTitle).toBeVisible();
  }

  /**
   * Fills the title search input and waits for the 400ms ScalaJS debounce.
   */
  async searchByTitle(title: string) {
    await this.inputTitle.fill(title);
    await this.page.waitForTimeout(500); // Account for 400ms ScalaJS debouncer
  }

  /**
   * Fills the organizer search input.
   */
  async searchByOrganizer(organizer: string) {
    await this.inputOrganizer.fill(organizer);
    await this.page.waitForTimeout(500);
  }

  /**
   * Fills the date filter input.
   */
  async searchByDate(date: string) {
    await this.inputDate.fill(date);
    await this.page.waitForTimeout(500);
  }

  /**
   * Selects search type filter ("all", "tourney", or "competition").
   */
  async selectTypeFilter(type: 'all' | 'tourney' | 'competition') {
    let target: Locator;
    let targetId: string;
    switch (type) {
      case 'tourney':
        target = this.radioTypeTourney;
        targetId = 'MainSearch_RadioTypeTourneyId';
        break;
      case 'competition':
        target = this.radioTypeComp;
        targetId = 'MainSearch_RadioTypeCompId';
        break;
      default:
        target = this.radioTypeAll;
        targetId = 'MainSearch_RadioTypeAllId';
        break;
    }
    const label = this.page.locator(`label[for="${targetId}"]`);
    if (await label.count() > 0) {
      await label.click();
    } else {
      await target.click({ force: true });
    }
    await this.page.waitForTimeout(300);
  }

  /**
   * Toggles the date sorting column.
   */
  async toggleDateSort() {
    await this.headerDateSort.click();
    await this.page.waitForTimeout(500);
  }

  /**
   * Clicks a result row by index (0-based).
   */
  async clickResult(index: number = 0) {
    await expect(this.resultRows.nth(index)).toBeVisible();
    await this.resultRows.nth(index).click();
  }

  /**
   * Asserts the results table state.
   */
  async assertResultCountText(expectedTextSubstr: string) {
    await expect(this.resultCount).toContainText(expectedTextSubstr);
  }
}
