import { Page, Locator, expect } from '@playwright/test';

/**
 * Page Object Model representing the MainView (Homepage / Landing Page).
 * Kapselt alle Buttons, Header, Footer und Navigations-Elemente der Startseite
 * unter Verwendung der ScalaJS HTML-IDs (#MainView_BtnOption1, #MainView_BtnSearch etc.).
 */
export class MainViewPage {
  readonly page: Page;

  // Key Action Buttons on Home Page (HTML-IDs generated by ScalaJS)
  readonly btnOption1: Locator;
  readonly btnOption2: Locator;
  readonly btnSearch: Locator;

  // Header & Navigation Elements
  readonly brandLogo: Locator;
  readonly navLoginBtn: Locator;
  readonly navManagementBtn: Locator;

  // Footer Links for Static Pages
  readonly footerPrivacyLink: Locator;
  readonly footerImpressumLink: Locator;
  readonly footerContactLink: Locator;
  readonly footerGtcLink: Locator;
  readonly footerPricingLink: Locator;

  // Static Content Area
  readonly staticPageTitle: Locator;
  readonly staticPageContent: Locator;

  constructor(page: Page) {
    this.page = page;

    // Encapsulate exact HTML-IDs generated by MainView.scala
    this.btnOption1 = page.locator('#MainView_BtnOption1');
    this.btnOption2 = page.locator('#MainView_BtnOption2');
    this.btnSearch = page.locator('#MainView_BtnSearch');

    // Header & Navigation
    this.brandLogo = page.locator('.navbar-brand');
    this.navLoginBtn = page.locator('#navbar-login, .navbar .btn:has-text("Anmelden"), .navbar .btn:has-text("Login")');
    this.navManagementBtn = page.locator('.navbar .btn:has-text("Management")');

    // Footer Links (using appLoadPage calls or href)
    this.footerPrivacyLink = page.locator('a[href*="privacy"], a[href*="dataprotection"]');
    this.footerImpressumLink = page.locator('a[href*="impressum"], a[href*="imprint"]');
    this.footerContactLink = page.locator('a[href*="contact"], a[href*="kontakt"]');
    this.footerGtcLink = page.locator('a[href*="gtc"], a[href*="agb"]');
    this.footerPricingLink = page.locator('a[href*="pricing"], a[href*="preise"]');

    // Content container for static pages
    this.staticPageTitle = page.locator('h1, h2.dp-title, .page-header-title');
    this.staticPageContent = page.locator('#content, .dp-container');
  }

  /**
   * Navigates directly to the MainView home URL.
   */
  async goto() {
    await this.page.goto('/');
    await this.page.waitForLoadState('domcontentloaded');
  }

  /**
   * Clicks the MainSearch button to open the search page.
   */
  async clickSearch() {
    await this.btnSearch.click();
    await this.page.waitForURL(/.*#MainSearch/);
  }

  /**
   * Clicks Option 1 (New Tournament / Demo Mode prompt).
   */
  async clickOption1() {
    await this.btnOption1.click();
  }

  /**
   * Clicks Option 2 (Quick Start / Demo Mode prompt).
   */
  async clickOption2() {
    await this.btnOption2.click();
  }

  /**
   * Asserts that essential homepage elements are visible.
   */
  async assertPageLoaded() {
    await expect(this.btnSearch).toBeVisible();
    await expect(this.btnOption1).toBeVisible();
    await expect(this.btnOption2).toBeVisible();
  }
}
