name: ${APP_NAME}

services:
  # traefik:
  #   image: localhost:5555/traefik:v2.11
  #   container_name: traefik-instance
  #   command:
  #     # Traefik Dashboard aktiv
  #     - "--api.dashboard=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--providers.docker.network=wordpress_web"

  #     # EntryPoints
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure.address=:443"

  #     # HTTP → HTTPS Umleitung
  #     - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  #     - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

  #     # Let's Encrypt ACME
  #     - "--certificatesresolvers.myresolver.acme.email=${MY_EMAIL}"
  #     - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
  #     - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
  #     - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"

  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock   # Zugriff auf Docker API
  #     - ./acme.json:/acme.json
  #   networks:
  #     - web

  wordpress:
    image: wp-gmp-image
    build:
      context: .
      dockerfile: wordpress/Dockerfile
    container_name: wp-gmp-instance
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'PLAY_SERVER_URL', "${PLAY_SERVER_URL}" );
    ports:
      - 8080:80
    volumes:
      - ./wp_data:/var/www/html
    # labels:
      # - "traefik.enable=true"
      # - "traefik.docker.network=wordpress_web"
      # - "traefik.http.routers.wordpress.rule=Host(`${MY_DOMAIN}`)"
      # - "traefik.http.routers.wordpress.entrypoints=websecure"
      # - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
      # - "traefik.http.routers.wordpress.tls=true"
      # - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    networks:
      - web
      - internal

  wp-cli:
    image: wordpress:cli
    container_name: wp-cli-instance
    user: root
    volumes:
      - ./wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - internal
    command: tail -f /dev/null # Container am Laufen halten


  db:
    image: mariadb:10.11
    container_name: wp-db-instance
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - internal


  playsrv: # PlayDemo Server:
    image: playsrv-image # Replace this with the actual image name of your Play Framework app
    container_name: playsrv-instance
    build:
      context: .
      dockerfile: playdemo/Dockerfile
      args:
        - APP_HOME=${APP_HOME}
        - PLAY_WP_URL=${PLAY_WP_URL}
        - PLAY_WP_CPT=${PLAY_WP_CPT}
        - APP_VERSION=${APP_VERSION}
        - DEMON_USER=${DEMON_USER}
        - DEMON_USERID=${DEMON_USERID}

    labels:
      MAINTAINER: ${APP_MAINTAINER}
      VENDOR: ${APP_VENDOR}
      IMAGE_DESCRIPTION: "This Dockerfile creates an image with the PlayDemo App running on it."
 
    environment:
      APP_VERSION: ${APP_VERSION}
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      APP_DATE: ${APP_DATE}   
      PLAY_LOGFILE_PATH: ${APP_HOME}/logs
      PLAY_PIDFILE_PATH: ${PLAY_PIDFILE_PATH}

      # environment read by application.conf
      DB_DEFAULT_URL: ${DB_DEFAULT_URL}
      DB_DEFAULT_DRIVER: ${DB_DEFAULT_DRIVER}
      DB_DEFAULT_USERNAME: ${DB_DEFAULT_USERNAME}
      DB_DEFAULT_PASSWORD: ${DB_DEFAULT_PASSWORD}
      
      PLAY_WP_URL: ${PLAY_WP_URL}
      PLAY_WP_CPT: ${PLAY_WP_CPT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      PLAY_HTTP_PORT: ${PLAY_HTTP_PORT}
      PLAY_HTTP_HOST: ${PLAY_HTTP_HOST}
      PLAY_HTTP_SECRET_KEY: ${PLAY_HTTP_SECRET_KEY}
      PLAY_MAILER_HOST: ${PLAY_MAILER_HOST}
      PLAY_MAILER_PORT: ${PLAY_MAILER_PORT}
      PLAY_MAILER_USER: ${PLAY_MAILER_USER}
      PLAY_MAILER_PASSWORD: ${PLAY_MAILER_PASSWORD}
      PLAY_MAILER_DEBUG: ${PLAY_MAILER_DEBUG}
      PLAY_MAILER_MOCK: ${PLAY_MAILER_MOCK}
    ports:
      - "${PLAY_HTTP_PORT}:${PLAY_HTTP_PORT}"      
    volumes:
      - "./logs:${APP_HOME}/logs:rw"
    depends_on:
      - db
    networks:
      - internal

  composer:
    image: composer:2
    container_name: composer-instance
    working_dir: /app
    volumes:
      - ./wp_data:/app
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - internal      

networks:
  web:
    external: false
  internal:
    external: false